name: Automated E2E Testing
on: 
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        env:
          VALID_EMAIL: ntkyen@stud.noroff.no
          VALID_PASSWORD: 12345678921323

        with:
          browser: electron
